on:
  push:
    branches:
      - "develop"
      - "staging"
      - "master"

env:
  GO_VERSION: "1.16"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: "Pull dependencies"
        run: go mod vendor
      - name: "Unit tests"
        run: make test
      - name: "Linter"
        run: make lint
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Calculate semver tag"
        id: semver-tag
        uses: wakatime/semver-action@master
        with:
          debug: true
      -
        # Run only for develop branch
        if: ${{ github.ref == 'refs/heads/develop' }}
        name: Changelog for develop
        uses: gandarez/changelog-action@v1.0.4
        id: changelog-develop
        with:
          current_tag: ${{ github.sha }}
          previous_tag: ${{ needs.version.outputs.ancestor_tag }}
          exclude: |
            ^Merge pull request .*
      -
        # Run only for master branch
        if: ${{ github.ref == 'refs/heads/master' }}
        name: Get related pull request
        uses: 8BitJonny/gh-get-current-pr@2.0.0
        id: changelog-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Prepare changelog
        id: changelog
        run: |
          changelog="${{ steps.changelog-develop.outputs.changelog || steps.changelog-release.outputs.pr_body }}"
          ./bin/prepare_changelog.sh $(echo ${GITHUB_REF#refs/heads/}) "$changelog"
      - name: "Create Release"
        uses: softprops/action-gh-release@master
        with:
          name: ${{ steps.semver-tag.outputs.semver_tag }}
          tag_name: ${{ steps.semver-tag.outputs.semver_tag }}
          body: "## Changelog\n${{ steps.changelog.outputs.pr_body }}"
          prerelease: ${{ steps.semver-tag.outputs.is_prerelease }}
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: "Slack notification"
        uses: 8398a7/action-slack@v3
        if: ${{ success() }}
        with:
          status: custom
          fields: message
          custom_payload: |
            {
              username: 'WakaTime Bot',
              icon_emoji: ':mega:',
              blocks: [
                {
                  type: 'section',
                  text: {
                    type: 'mrkdwn',
                    text: `New <https://github.com/gandarez/release-pipeline-demo|release-pipeline-demo> version <https://github.com/gandarez/release-pipeline-demo/releases/tag/${{ needs.semver-tag.outputs.semver_tag }}|${{ needs.semver-tag.outputs.semver_tag }}> released`
                  }
                },
                {
                  type: 'context',
                  elements: [
                    {
                      type: 'mrkdwn',
                      text: `${{ steps.changelog.outputs.slack }}`
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
